spring:
  redis:
    host: 47.108.28.239
    port: 6390
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间（负数表示没有限制）
        max-idle: 5
        min-idle: 0
