server:
  port: 9601

currency:
  swagger:
    enabled: true
    base-package: com.qingfeng.cms
    description: 第二课堂——信息管理模块

spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5670
    host: 101.42.160.177
    virtual-host: /
    #开启消息确认模式
    publisher-returns: true
    publisher-confirms: true
    template:
      # 消息发送失败返回到队列中, yml需要配置 publisher-returns: true
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual #手动ACK
        default-requeue-rejected: false #个字段一定要设置成 false 不然无法消费的数据不会进入死信队列的
        concurrency: 1 #同一个队列启动几个消费者
        max-concurrency: 5 #启动消费者最大数量
        prefetch: 1 #限制每次发送一条数据
        retry:
          enabled: true #是否支持重试

# log config
logging:
  config: classpath:logback.xml


# xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: qingfeng_java # xxl-job, access token
    executor:
      appname: cms-community-activities-job-executor # 执行器的名称，如果要部署多个节点，执行器的名称必须相同
      # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      # xxl-job executor server-info
      ip:
      port: 9611  # 内部调用的端口
      # xxl-job executor log-path
      logpath: ./data/applogs/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30

# 配置全局的逻辑删除值
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


