# 配置网关路由
spring:
  cloud:
    gateway:
      routes:
        # 权限服务相关的网关路由
        - id: currency_auth_server # 网关Id
          uri: lb://currency-auth-server
          predicates:
            - Path=/api/authority/**
          filters: # 指定路径重写
            - RewritePath=/api/authority/(?<segment>.*),/$\{segment}

        # 文件服务相关的网关路由
        - id: cms_file # 网关Id
          uri: lb://cms-file
          predicates:
            - Path=/api/file/**
          filters: # 指定路径重写
            - RewritePath=/api/file/(?<segment>.*),/file/$\{segment}

        # 学分修读方案服务的网关路由
        - id: cms_plan_standard # 网关Id
          uri: lb://cms-plan-standard
          predicates:
            - Path=/api/plan/**
          filters: # 指定路径重写
            - RewritePath=/api/plan/(?<segment>.*),/$\{segment}

        # 信息管理服务的网关路由
        - id: cms-message-control # 网关Id
          uri: lb://cms-message-control
          predicates:
            - Path=/api/message/**
          filters: # 指定路径重写
            - RewritePath=/api/message/(?<segment>.*),/$\{segment}

        # 社团活动管理服务的网关路由
        - id: cms-community-activities # 网关Id
          uri: lb://cms-community-activities
          predicates:
            - Path=/api/active/**
          filters: # 指定路径重写
            - RewritePath=/api/active/(?<segment>.*),/$\{segment}

        # 项目管理服务的网关路由
        - id: cms-item-manage # 网关Id
          uri: lb://cms-item-manage
          predicates:
            - Path=/api/item/**
          filters: # 指定路径重写
            - RewritePath=/api/item/(?<segment>.*),/$\{segment}
