server:
  port: 8080


#指定文件上传的位置
photo:
  file:
    dir: D:\IDEA版java相关知识学习\web项目开发\基于SpringBoot的攀枝花学院第二课堂素质拓展学分管理系统\前后端分离\前端\攀枝花学院第二课堂素质拓展学分管理系统\static\photo

logging:
  level:
    root: DEBUG

spring:
  servlet:
    multipart:
      # 单个文件上传大小
      max-request-size: 50MB
      # 一次请求的多个文件大小
      max-file-size: 50MB
