server:
  port: 9701

currency:
  swagger:
    enabled: true
    base-package: com.qingfeng.cms
    description: 第二课堂——项目管理模块


# 配置全局的逻辑删除值
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

